use std::path::Path;
use serde::{Deserialize, Serialize};

use crate::error::AppError;

/// Non-secret tfvars fields — serialised as JSON into clusters.tfvars_json.
/// Secrets (passwords, paywall creds) are stored in macOS Keychain only.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TfvarsConfig {
    pub aws_region: String,
    pub environment: String,
    pub owner_tag: String,
    pub operator_ingress_cidrs: Vec<String>,
    pub vpc_cidr: String,
    pub public_subnets: Vec<String>,
    pub private_subnets: Vec<String>,
    pub azs: Vec<String>,
    pub private_dns_domain: String,
    pub master_count: u32,
    pub worker_count: u32,
    pub edge_count: u32,
    pub worker_data_disk_count: u32,
    pub worker_data_disk_gb: u32,
    pub master_data_disk_gb: u32,
    pub bastion_instance_type: String,
    pub ipa_instance_type: String,
    pub util_instance_type: String,
    pub master_instance_type: String,
    pub worker_instance_type: String,
    pub edge_instance_type: String,
    pub ssh_key_name: String,
    /// "freeipa" | "ldap" | "ad" — controls whether FreeIPA is installed
    #[serde(default = "default_directory_type")]
    pub directory_type: String,
    /// External LDAP/AD server URL (ldap/ad modes only)
    #[serde(default)]
    pub ldap_url: Option<String>,
    /// LDAP bind DN Cloudera Manager uses for directory auth
    #[serde(default)]
    pub ldap_bind_dn: Option<String>,
    /// LDAP search base DN
    #[serde(default)]
    pub ldap_base_dn: Option<String>,
}

fn default_directory_type() -> String { "freeipa".to_string() }

impl Default for TfvarsConfig {
    fn default() -> Self {
        Self {
            aws_region: "ap-south-1".into(),
            environment: "prod".into(),
            owner_tag: "platform-team".into(),
            operator_ingress_cidrs: vec![],
            vpc_cidr: "10.42.0.0/16".into(),
            public_subnets: vec!["10.42.0.0/24".into()],
            private_subnets: vec!["10.42.10.0/24".into()],
            azs: vec!["ap-south-1a".into()],
            private_dns_domain: "cdp.prod.internal".into(),
            master_count: 3,
            worker_count: 5,
            edge_count: 1,
            worker_data_disk_count: 4,
            worker_data_disk_gb: 1000,
            master_data_disk_gb: 500,
            bastion_instance_type: "t3.small".into(),
            ipa_instance_type: "m5.large".into(),
            util_instance_type: "m5.2xlarge".into(),
            master_instance_type: "m5.2xlarge".into(),
            worker_instance_type: "r5.4xlarge".into(),
            edge_instance_type: "m5.xlarge".into(),
            ssh_key_name: "cdp732".into(),
            directory_type: "freeipa".into(),
            ldap_url: None,
            ldap_bind_dn: None,
            ldap_base_dn: None,
        }
    }
}

/// Writes terraform/terraform.tfvars and ansible/extra-vars.yml into the
/// installer repo. Reads secrets from macOS Keychain using the cluster_id.
/// IMPORTANT: does not log file contents.
pub fn write_tfvars(
    cluster_id: &str,
    cluster_name: &str,
    repo_path: &Path,
    cfg: &TfvarsConfig,
) -> Result<(), AppError> {
    // Fetch secrets from Keychain
    let service = "com.partomia.cdp-launcher";
    let get = |key: &str| -> Result<String, AppError> {
        let entry_name = format!("{cluster_id}:{key}");
        keyring::Entry::new(service, &entry_name)
            .map_err(|e| AppError::Keychain(e.to_string()))?
            .get_password()
            .map_err(|e| AppError::Keychain(format!("key {key}: {e}")))
    };

    let repo_user = get("PAYWALL_USER")?;
    let repo_pass = get("PAYWALL_PASS")?;
    let ds_pass   = get("DS_PASSWORD").unwrap_or_default();
    let adm_pass  = get("ADM_PASSWORD").unwrap_or_default();
    let cm_pass   = get("CM_ADMIN_PASSWORD")?;
    let db_pass   = get("DB_ROOT_PASSWORD")?;

    // Build CIDRs string: ["a/32", "b/32"]
    let cidrs_hcl = cfg
        .operator_ingress_cidrs
        .iter()
        .map(|c| format!("  \"{c}\""))
        .collect::<Vec<_>>()
        .join(",\n");

    let subnets_hcl = |v: &[String]| {
        v.iter().map(|s| format!("\"{s}\"")).collect::<Vec<_>>().join(", ")
    };

    let content = format!(
        r#"# Generated by CDP Launcher — do not edit by hand.
# Secrets are rendered from macOS Keychain at install time.

# ── AWS ──────────────────────────────────────────────────────────────────
aws_region  = "{aws_region}"
environment = "{environment}"
owner_tag   = "{owner_tag}"

operator_ingress_cidrs = [
{cidrs_hcl}
]

# ── Networking ───────────────────────────────────────────────────────────
vpc_cidr           = "{vpc_cidr}"
public_subnets     = [{pub_subnets}]
private_subnets    = [{priv_subnets}]
azs                = [{azs}]
private_dns_domain = "{dns_domain}"

# ── Topology ─────────────────────────────────────────────────────────────
master_count           = {master_count}
worker_count           = {worker_count}
edge_count             = {edge_count}
worker_data_disk_count = {worker_data_disk_count}
worker_data_disk_gb    = {worker_data_disk_gb}
master_data_disk_gb    = {master_data_disk_gb}

# ── Instance types ────────────────────────────────────────────────────────
bastion_instance_type = "{bastion}"
ipa_instance_type     = "{ipa}"
util_instance_type    = "{util}"
master_instance_type  = "{master}"
worker_instance_type  = "{worker}"
edge_instance_type    = "{edge}"

# ── AMI ──────────────────────────────────────────────────────────────────
rhel9_ami = null

# ── SSH ──────────────────────────────────────────────────────────────────
ssh_key_name = "{ssh_key}"

# ── Cloudera paywall ─────────────────────────────────────────────────────
cdp_repo_user = "{repo_user}"
cdp_repo_pass = "{repo_pass}"

# ── Bootstrap passwords ───────────────────────────────────────────────────
cdp_ds_password       = "{ds_pass}"
cdp_adm_password      = "{adm_pass}"
cdp_cm_admin_password = "{cm_pass}"
cdp_db_root_password  = "{db_pass}"
"#,
        aws_region = cfg.aws_region,
        environment = cfg.environment,
        owner_tag = cfg.owner_tag,
        cidrs_hcl = cidrs_hcl,
        vpc_cidr = cfg.vpc_cidr,
        pub_subnets = subnets_hcl(&cfg.public_subnets),
        priv_subnets = subnets_hcl(&cfg.private_subnets),
        azs = subnets_hcl(&cfg.azs),
        dns_domain = cfg.private_dns_domain,
        master_count = cfg.master_count,
        worker_count = cfg.worker_count,
        edge_count = cfg.edge_count,
        worker_data_disk_count = cfg.worker_data_disk_count,
        worker_data_disk_gb = cfg.worker_data_disk_gb,
        master_data_disk_gb = cfg.master_data_disk_gb,
        bastion = cfg.bastion_instance_type,
        ipa = cfg.ipa_instance_type,
        util = cfg.util_instance_type,
        master = cfg.master_instance_type,
        worker = cfg.worker_instance_type,
        edge = cfg.edge_instance_type,
        ssh_key = cfg.ssh_key_name.trim_end_matches(".pem"),
        repo_user = repo_user,
        repo_pass = repo_pass,
        ds_pass = ds_pass,
        adm_pass = adm_pass,
        cm_pass = cm_pass,
        db_pass = db_pass,
    );

    let tfvars_path = repo_path.join("terraform").join("terraform.tfvars");
    tracing::info!("writing terraform.tfvars to {}", tfvars_path.display());
    std::fs::write(&tfvars_path, content)?;

    // Write canonical Ansible vars expected by the current installer repo.
    write_group_vars(cluster_id, cluster_name, repo_path, cfg)?;
    // Keep extra-vars.yml as a small overlay for directory-mode-specific values.
    write_extra_vars(cluster_id, repo_path, cfg)?;

    Ok(())
}

fn uppercase_realm(domain: &str) -> String {
    domain.to_ascii_uppercase()
}

fn ldap_bind_user_from_dn(bind_dn: &str) -> String {
    bind_dn
        .split(',')
        .next()
        .and_then(|part| part.strip_prefix("cn=").or_else(|| part.strip_prefix("CN=")))
        .unwrap_or("cm-bind")
        .to_string()
}

fn write_group_vars(
    cluster_id: &str,
    cluster_name: &str,
    repo_path: &Path,
    cfg: &TfvarsConfig,
) -> Result<(), AppError> {
    let service = "com.partomia.cdp-launcher";
    let get_opt = |key: &str| -> String {
        let entry_name = format!("{cluster_id}:{key}");
        keyring::Entry::new(service, &entry_name)
            .ok()
            .and_then(|e| e.get_password().ok())
            .unwrap_or_default()
    };

    let domain = cfg.private_dns_domain.trim();
    let realm = uppercase_realm(domain);
    let ipa_host = format!("ipa1.{domain}");
    let cm_host = format!("util1.{domain}");
    let db_host = cm_host.clone();
    let ldap_bind_dn = cfg.ldap_bind_dn.as_deref().unwrap_or("");
    let ldap_bind_user = ldap_bind_user_from_dn(ldap_bind_dn);

    let repo_user = get_opt("PAYWALL_USER");
    let repo_pass = get_opt("PAYWALL_PASS");
    let ds_pass = get_opt("DS_PASSWORD");
    let adm_pass = get_opt("ADM_PASSWORD");
    let ldap_bind_password = get_opt("LDAP_BIND_PASSWORD");
    let cm_pass = get_opt("CM_ADMIN_PASSWORD");
    let db_root_pass = get_opt("DB_ROOT_PASSWORD");

    // The launcher currently captures only a small secret set, so reuse the
    // root/admin secrets for the per-service values the installer now expects.
    let shared_db_pass = if db_root_pass.is_empty() {
        "REPLACE_ME".to_string()
    } else {
        db_root_pass.clone()
    };
    let krb_admin_password = if adm_pass.is_empty() {
        ldap_bind_password.clone()
    } else {
        adm_pass.clone()
    };
    let effective_ldap_bind_password = if ldap_bind_password.is_empty() {
        adm_pass.clone()
    } else {
        ldap_bind_password
    };

    let content = format!(
        r#"---
# Generated by CDP Launcher — do not edit by hand.
ansible_python_interpreter: "/usr/bin/python3"

# ── Identity / DNS / Kerberos ──────────────────────────────────────────────
cdp_domain: "{domain}"
cdp_realm: "{realm}"
cdp_vpc_cidr: "{vpc_cidr}"
cdp_ipa_host: "{ipa_host}"
cdp_cm_host: "{cm_host}"
cdp_db_host: "{db_host}"
cdp_krb_admin: "admin"
cdp_ldap_bind_user: "{ldap_bind_user}"
cdp_cluster_name: "{cluster_name}"
cdp_kerberos_datanode_transceiver_port: 1004
cdp_kerberos_datanode_web_port: 1006
cdp_cluster_template_enable_kerberos: false

# ── Cloudera versions (pinned) ─────────────────────────────────────────────
cdp_cm_version: "7.13.2"
cdp_runtime_version: "7.3.2.0"
cdp_jdk_pkg: "java-17-openjdk-devel"

# ── Module streams ─────────────────────────────────────────────────────────
cdp_mariadb_module: "mariadb:10.6"
cdp_pg_module: "postgresql:14"
cdp_py_module: "python:3.11"

# ── Cloudera paywall credentials ───────────────────────────────────────────
cdp_repo_user: "{repo_user}"
cdp_repo_pass: "{repo_pass}"

# ── Admin / directory / license ────────────────────────────────────────────
cdp_ds_password: "{ds_pass}"
cdp_adm_password: "{adm_pass}"
cdp_krb_admin_password: "{krb_admin_password}"
cdp_ldap_bind_password: "{effective_ldap_bind_password}"
cdp_cm_admin_password: "{cm_pass}"
cdp_license_file: "/opt/cloudera/license.txt"
cdp_license_local_path: ""

# ── Database passwords ─────────────────────────────────────────────────────
cdp_db_root_password: "{db_root_pass}"
cdp_db_scm_password: "{shared_db_pass}"
cdp_db_rman_password: "{shared_db_pass}"
cdp_db_hive_password: "{shared_db_pass}"
cdp_db_hue_password: "{shared_db_pass}"
cdp_db_oozie_password: "{shared_db_pass}"
cdp_db_ranger_password: "{shared_db_pass}"
cdp_db_rangerkms_password: "{shared_db_pass}"
cdp_db_schemareg_password: "{shared_db_pass}"
cdp_db_smm_password: "{shared_db_pass}"
cdp_db_qmadmin_password: "{shared_db_pass}"
"#,
        domain = domain,
        realm = realm,
        vpc_cidr = cfg.vpc_cidr,
        ipa_host = ipa_host,
        cm_host = cm_host,
        db_host = db_host,
        ldap_bind_user = ldap_bind_user,
        cluster_name = cluster_name,
        repo_user = repo_user,
        repo_pass = repo_pass,
        ds_pass = ds_pass,
        adm_pass = adm_pass,
        krb_admin_password = krb_admin_password,
        effective_ldap_bind_password = effective_ldap_bind_password,
        cm_pass = cm_pass,
        db_root_pass = db_root_pass,
        shared_db_pass = shared_db_pass,
    );

    let group_vars_dir = repo_path.join("ansible").join("group_vars");
    std::fs::create_dir_all(&group_vars_dir)?;
    let path = group_vars_dir.join("all.yml");
    tracing::info!("writing ansible/group_vars/all.yml for {}", cluster_name);
    std::fs::write(&path, content)?;
    Ok(())
}

/// Writes ansible/extra-vars.yml with directory type and LDAP/AD config.
/// These variables are loaded by every `ansible-playbook` invocation via
/// the Makefile rule:  ifneq ($(wildcard ansible/extra-vars.yml),)
///                       ANS_FLAGS += -e @ansible/extra-vars.yml
fn write_extra_vars(
    cluster_id: &str,
    repo_path: &Path,
    cfg: &TfvarsConfig,
) -> Result<(), AppError> {
    let service = "com.partomia.cdp-launcher";
    let get_opt = |key: &str| -> String {
        let entry_name = format!("{cluster_id}:{key}");
        keyring::Entry::new(service, &entry_name)
            .ok()
            .and_then(|e| e.get_password().ok())
            .unwrap_or_default()
    };

    let dir_type = &cfg.directory_type;
    let is_external = dir_type == "ldap" || dir_type == "ad";

    let mut lines = vec![
        "# Generated by CDP Launcher — do not edit by hand.".to_string(),
        "# Loaded by ansible-playbook via Makefile: -e @ansible/extra-vars.yml".to_string(),
        String::new(),
        format!("cdp_directory_type: \"{}\"", dir_type),
    ];

    if is_external {
        let ldap_url      = cfg.ldap_url.as_deref().unwrap_or("");
        let ldap_bind_dn  = cfg.ldap_bind_dn.as_deref().unwrap_or("");
        let ldap_base_dn  = cfg.ldap_base_dn.as_deref().unwrap_or("");
        let ldap_bind_pw  = get_opt("LDAP_BIND_PASSWORD");

        lines.push(String::new());
        lines.push("# External directory connection".to_string());
        lines.push(format!("cdp_ldap_url: \"{}\"", ldap_url));
        lines.push(format!("cdp_ldap_bind_dn: \"{}\"", ldap_bind_dn));
        lines.push(format!("cdp_ldap_base_dn: \"{}\"", ldap_base_dn));
        lines.push(format!("cdp_ldap_bind_password: \"{}\"", ldap_bind_pw));

        // Derive a simple ldap_bind_user from the CN in the bind DN
        let bind_user = ldap_bind_user_from_dn(ldap_bind_dn);
        lines.push(format!("cdp_ldap_bind_user: \"{}\"", bind_user));
    }

    let content = lines.join("\n") + "\n";
    let path = repo_path.join("ansible").join("extra-vars.yml");
    tracing::info!("writing ansible/extra-vars.yml (directory_type={})", dir_type);
    std::fs::write(&path, content)?;
    Ok(())
}
