use std::path::Path;
use serde::{Deserialize, Serialize};

use crate::error::AppError;

/// Non-secret tfvars fields — serialised as JSON into clusters.tfvars_json.
/// Secrets (passwords, paywall creds) are stored in macOS Keychain only.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TfvarsConfig {
    pub aws_region: String,
    pub environment: String,
    pub owner_tag: String,
    pub operator_ingress_cidrs: Vec<String>,
    pub vpc_cidr: String,
    pub public_subnets: Vec<String>,
    pub private_subnets: Vec<String>,
    pub azs: Vec<String>,
    pub private_dns_domain: String,
    pub master_count: u32,
    pub worker_count: u32,
    pub edge_count: u32,
    pub worker_data_disk_count: u32,
    pub worker_data_disk_gb: u32,
    pub master_data_disk_gb: u32,
    pub bastion_instance_type: String,
    pub ipa_instance_type: String,
    pub util_instance_type: String,
    pub master_instance_type: String,
    pub worker_instance_type: String,
    pub edge_instance_type: String,
    pub ssh_key_name: String,
}

impl Default for TfvarsConfig {
    fn default() -> Self {
        Self {
            aws_region: "ap-south-1".into(),
            environment: "prod".into(),
            owner_tag: "platform-team".into(),
            operator_ingress_cidrs: vec![],
            vpc_cidr: "10.42.0.0/16".into(),
            public_subnets: vec!["10.42.0.0/24".into()],
            private_subnets: vec!["10.42.10.0/24".into()],
            azs: vec!["ap-south-1a".into()],
            private_dns_domain: "cdp.prod.internal".into(),
            master_count: 3,
            worker_count: 5,
            edge_count: 1,
            worker_data_disk_count: 4,
            worker_data_disk_gb: 1000,
            master_data_disk_gb: 500,
            bastion_instance_type: "t3.small".into(),
            ipa_instance_type: "m5.large".into(),
            util_instance_type: "m5.2xlarge".into(),
            master_instance_type: "m5.2xlarge".into(),
            worker_instance_type: "r5.4xlarge".into(),
            edge_instance_type: "m5.xlarge".into(),
            ssh_key_name: "cdp732".into(),
        }
    }
}

/// Writes terraform/terraform.tfvars into the installer repo.
/// Reads secrets from macOS Keychain using the cluster_id.
/// IMPORTANT: does not log the file contents.
pub fn write_tfvars(
    cluster_id: &str,
    repo_path: &Path,
    cfg: &TfvarsConfig,
) -> Result<(), AppError> {
    // Fetch secrets from Keychain
    let service = "com.partomia.cdp-launcher";
    let get = |key: &str| -> Result<String, AppError> {
        let entry_name = format!("{cluster_id}:{key}");
        keyring::Entry::new(service, &entry_name)
            .map_err(|e| AppError::Keychain(e.to_string()))?
            .get_password()
            .map_err(|e| AppError::Keychain(format!("key {key}: {e}")))
    };

    let repo_user = get("PAYWALL_USER")?;
    let repo_pass = get("PAYWALL_PASS")?;
    let ds_pass   = get("DS_PASSWORD")?;
    let adm_pass  = get("ADM_PASSWORD")?;
    let cm_pass   = get("CM_ADMIN_PASSWORD")?;
    let db_pass   = get("DB_ROOT_PASSWORD")?;

    // Build CIDRs string: ["a/32", "b/32"]
    let cidrs_hcl = cfg
        .operator_ingress_cidrs
        .iter()
        .map(|c| format!("  \"{c}\""))
        .collect::<Vec<_>>()
        .join(",\n");

    let subnets_hcl = |v: &[String]| {
        v.iter().map(|s| format!("\"{s}\"")).collect::<Vec<_>>().join(", ")
    };

    // rhel9_ami omitted → null
    let content = format!(
        r#"# Generated by CDP Launcher — do not edit by hand.
# Secrets are rendered from macOS Keychain at install time.

# ── AWS ──────────────────────────────────────────────────────────────────
aws_region  = "{aws_region}"
environment = "{environment}"
owner_tag   = "{owner_tag}"

operator_ingress_cidrs = [
{cidrs_hcl}
]

# ── Networking ───────────────────────────────────────────────────────────
vpc_cidr           = "{vpc_cidr}"
public_subnets     = [{pub_subnets}]
private_subnets    = [{priv_subnets}]
azs                = [{azs}]
private_dns_domain = "{dns_domain}"

# ── Topology ─────────────────────────────────────────────────────────────
master_count           = {master_count}
worker_count           = {worker_count}
edge_count             = {edge_count}
worker_data_disk_count = {worker_data_disk_count}
worker_data_disk_gb    = {worker_data_disk_gb}
master_data_disk_gb    = {master_data_disk_gb}

# ── Instance types ────────────────────────────────────────────────────────
bastion_instance_type = "{bastion}"
ipa_instance_type     = "{ipa}"
util_instance_type    = "{util}"
master_instance_type  = "{master}"
worker_instance_type  = "{worker}"
edge_instance_type    = "{edge}"

# ── AMI ──────────────────────────────────────────────────────────────────
rhel9_ami = null

# ── SSH ──────────────────────────────────────────────────────────────────
ssh_key_name = "{ssh_key}"

# ── Cloudera paywall ─────────────────────────────────────────────────────
cdp_repo_user = "{repo_user}"
cdp_repo_pass = "{repo_pass}"

# ── Bootstrap passwords ───────────────────────────────────────────────────
cdp_ds_password       = "{ds_pass}"
cdp_adm_password      = "{adm_pass}"
cdp_cm_admin_password = "{cm_pass}"
cdp_db_root_password  = "{db_pass}"
"#,
        aws_region = cfg.aws_region,
        environment = cfg.environment,
        owner_tag = cfg.owner_tag,
        cidrs_hcl = cidrs_hcl,
        vpc_cidr = cfg.vpc_cidr,
        pub_subnets = subnets_hcl(&cfg.public_subnets),
        priv_subnets = subnets_hcl(&cfg.private_subnets),
        azs = subnets_hcl(&cfg.azs),
        dns_domain = cfg.private_dns_domain,
        master_count = cfg.master_count,
        worker_count = cfg.worker_count,
        edge_count = cfg.edge_count,
        worker_data_disk_count = cfg.worker_data_disk_count,
        worker_data_disk_gb = cfg.worker_data_disk_gb,
        master_data_disk_gb = cfg.master_data_disk_gb,
        bastion = cfg.bastion_instance_type,
        ipa = cfg.ipa_instance_type,
        util = cfg.util_instance_type,
        master = cfg.master_instance_type,
        worker = cfg.worker_instance_type,
        edge = cfg.edge_instance_type,
        ssh_key = cfg.ssh_key_name.trim_end_matches(".pem"),
        repo_user = repo_user,
        repo_pass = repo_pass,
        ds_pass = ds_pass,
        adm_pass = adm_pass,
        cm_pass = cm_pass,
        db_pass = db_pass,
    );

    let tfvars_path = repo_path.join("terraform").join("terraform.tfvars");
    tracing::info!("writing terraform.tfvars to {}", tfvars_path.display());
    std::fs::write(&tfvars_path, content)?;
    Ok(())
}
